export const projects = [
  {
    name: '',
    year: 2019,
    featuring: 'Aude Bourgine',
    featuring2: '',
    featuring3: '',
    services: `Projet vitrines Coral Eternal`,
    link: 'aude-bourgine',
    image: 'images/ACCESSOIRES ET DECORS/AUDE BOURGINE 2019/hermes-rouge.webp',
    alt: 'Aide à la fabrication de l’oeuvre « Coral Eternal » de l’artiste Aude Bourgine',
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2019,
    featuring: '',
    featuring2: '',
    featuring3: '',
    services: `Projet Hybride`,
    link: 'hybride',
    image: 'images/ACCESSOIRES ET DECORS/HYBRIDE/face.webp',
    alt: `A l'occasion des 500 ans de la mort de Léonard de Vinci. Pièce inspirée de son oeuvre et de ses recherches sur l'eau, le vol des oiseaux, l'anatomie, le dessin...`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2019,
    featuring: '',
    featuring2: '',
    featuring3: 'Isabelle Quéhé',
    services: `Projet Parures, objets d'art à porter`,
    link: 'parures',
    image: 'images/ACCESSOIRES ET DECORS/PARURES/affiche.webp',
    alt: `Création de deux pièces pour l'exposition "Parures, objets d'art à porter" conçue par Isabelle Quéhé.`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2020,
    featuring: 'Frank Oettgen',
    featuring2: 'Laura Reboul',
    featuring3: 'La compagnie Les Grandes Personnes',
    services: `Projet Cafêtes Mobiles`,
    link: 'cafete',
    image: 'images/ACCESSOIRES ET DECORS/CAFETE/cafete-two.webp',
    alt: 'Construction à la Villa Mais D’Ici, Aubervillers',
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2021,
    featuring: 'Alain Burkarth & Guillaume Béguinot',
    featuring2: 'Camille Boitel',
    featuring3: `La compagnie L'immédiat`,
    services: `Projet Le Poids des choses`,
    link: 'le-poids-des-choses',
    image: 'images/ACCESSOIRES ET DECORS/LPDC/photo1.webp',
    alt: `Collecte d'objets anciens, fabrication d'accessoires, trucage`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2021,
    featuring: '',
    featuring2: 'La compagnie Le Ballon Vert',
    featuring3: `La compagnie Les Plastiqueurs`,
    services: `Projet La Constellation de l'Ours`,
    link: 'la-constellation-de-lours',
    image:
      'images/ACCESSOIRES ET DECORS/CONSTELLATION DE LOURS/Julien Helie Photographe/decor.webp',
    alt: `Fabrication d'accessoires et de décors, montage, démontage`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2021,
    featuring: '',
    featuring2: '',
    featuring3: ``,
    services: `Projet Défilé Albert de Mun`,
    link: 'albert-de-mun',
    image: 'images/ACCESSOIRES ET DECORS/MUN/photo1.webp',
    alt: `Construction, préparation des chassis, patines`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2022,
    featuring: 'Vincent Gadras',
    featuring2: 'Camille Boitel',
    featuring3: `La compagnie L'immédiat`,
    services: `Projet spectacle`,
    link: 'fissure',
    image: 'images/ACCESSOIRES ET DECORS/FISSURE/photo-rouge.webp',
    alt: `Collecte d'objets anciens, fabrication d'accessoires, trucage, décors`,
    filter: 'accessoires&decors',
  },
  {
    name: '',
    year: 2022,
    featuring: '',
    featuring2: 'Alexander Zeldin',
    featuring3: `L’Odéon-Théâtre de l’Europe`,
    services: `Projet Une mort dans la famille`,
    link: 'une-mort-dans-la-famille',
    image: 'images/ACCESSOIRES ET DECORS/UMDLF/photo2.webp',
    alt: `Participation à la réalisation des accessoires de jeu et mobiliers.`,
    filter: 'accessoires&decors',
  },
];
